# Generated by Django 3.2.7 on 2021-09-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(default='country_code', max_length=100)),
                ('destination', models.CharField(default='ES', max_length=3)),
                ('origin_type', models.CharField(default='country_code', max_length=100)),
                ('origin', models.CharField(default='DE', max_length=3)),
                ('arrival_date', models.DateField(default='2020-10-15')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='venture.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(default='country_code', max_length=100)),
                ('location', models.CharField(default='DE', max_length=3)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='venture.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(default='LH', max_length=3)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='venture.trip')),
            ],
        ),
    ]
