# Generated by Django 3.2.7 on 2021-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='location_type',
            field=models.CharField(default='country_code', max_length=15),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='destination_type',
            field=models.CharField(default='country_code', max_length=15),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='origin_type',
            field=models.CharField(default='country_code', max_length=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(default='blank'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo_url',
            field=models.TextField(default='blank'),
        ),
    ]
